// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	nsq "github.com/nsqio/go-nsq"
	mock "github.com/stretchr/testify/mock"
)

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

// AddHandler provides a mock function with given fields: _a0
func (_m *Consumer) AddHandler(_a0 nsq.Handler) {
	_m.Called(_a0)
}

// ConnectToNSQD provides a mock function with given fields: _a0
func (_m *Consumer) ConnectToNSQD(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectToNSQLookupd provides a mock function with given fields: _a0
func (_m *Consumer) ConnectToNSQLookupd(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Consumer) Stop() {
	_m.Called()
}

type mockConstructorTestingTNewConsumer interface {
	mock.TestingT
	Cleanup(func())
}

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConsumer(t mockConstructorTestingTNewConsumer) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
