// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	nsq "github.com/nsqio/go-nsq"
	mock "github.com/stretchr/testify/mock"
)

// HandlerFunc is an autogenerated mock type for the HandlerFunc type
type HandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: message
func (_m *HandlerFunc) Execute(message *nsq.Message) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(*nsq.Message) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
