// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Output provides a mock function with given fields: calldepth, s
func (_m *Logger) Output(calldepth int, s string) error {
	ret := _m.Called(calldepth, s)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(calldepth, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
