// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// DeferredPublish provides a mock function with given fields: topic, delay, body
func (_m *Producer) DeferredPublish(topic string, delay time.Duration, body []byte) error {
	ret := _m.Called(topic, delay, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Duration, []byte) error); ok {
		r0 = rf(topic, delay, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: topic, message
func (_m *Producer) Publish(topic string, message []byte) error {
	ret := _m.Called(topic, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(topic, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Producer) Stop() {
	_m.Called()
}

type mockConstructorTestingTNewProducer interface {
	mock.TestingT
	Cleanup(func())
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProducer(t mockConstructorTestingTNewProducer) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
