package trouble

const (
	REASON_EMAIL_NOT_FOUND             = "EMAIL_NOT_FOUND"
	REASON_EMAIL_ALREADY_EXIST         = "EMAIL_ALREADY_EXIST"
	REASON_PASSWORD_INCORRECT          = "PASSWORD_INCORRECT"
	REASON_ACCESS_TOKEN_INVALID        = "ACCESS_TOKEN_INVALID"
	REASON_ACCESS_TOKEN_EXPIRED        = "ACCESS_TOKEN_EXPIRED"
	REASON_REFRESH_TOKEN_INVALID       = "REFRESH_TOKEN_INVALID"
	REASON_REFRESH_TOKEN_MISMATCH      = "REFRESH_TOKEN_MISMATCH"
	REASON_REFRESH_TOKEN_EXPIRED       = "REFRESH_TOKEN_EXPIRED"
	REASON_GOOGLE_ACCESS_TOKEN_INVALID = "GOOGLE_ACCESS_TOKEN_INVALID"
	REASON_INTERNAL_SERVER_ERROR       = "INTERNAL_SERVER_ERROR"
)
