// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DeleteSeratUseCaser is an autogenerated mock type for the DeleteSeratUseCaser type
type DeleteSeratUseCaser struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, id
func (_m *DeleteSeratUseCaser) Exec(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
