// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	api "github.com/fikrirnurhidayat/kasusastran/api"
	manager "github.com/fikrirnurhidayat/kasusastran/app/domain/manager"
	mock "github.com/stretchr/testify/mock"
)

// PaginationManager is an autogenerated mock type for the PaginationManager type
type PaginationManager struct {
	mock.Mock
}

// FromIncomingRequest provides a mock function with given fields: _a0
func (_m *PaginationManager) FromIncomingRequest(_a0 *api.RequestPagination) *manager.Pagination {
	ret := _m.Called(_a0)

	var r0 *manager.Pagination
	if rf, ok := ret.Get(0).(func(*api.RequestPagination) *manager.Pagination); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager.Pagination)
		}
	}

	return r0
}

// NewOutgoingResponse provides a mock function with given fields: _a0
func (_m *PaginationManager) NewOutgoingResponse(_a0 *manager.Pagination) *api.ResponsePagination {
	ret := _m.Called(_a0)

	var r0 *api.ResponsePagination
	if rf, ok := ret.Get(0).(func(*manager.Pagination) *api.ResponsePagination); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ResponsePagination)
		}
	}

	return r0
}
