// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	manager "github.com/fikrirnurhidayat/kasusastran/app/domain/manager"
	mock "github.com/stretchr/testify/mock"
)

// PaginationManagerSetter is an autogenerated mock type for the PaginationManagerSetter type
type PaginationManagerSetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *PaginationManagerSetter) Execute(_a0 *manager.PaginationManagerImpl) {
	_m.Called(_a0)
}
