// Code generated by sqlc. DO NOT EDIT.

package query

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Serat struct {
	ID uuid.UUID `json:"id"`
	// The title of a Serat.
	Title string `json:"title"`
	// The summary of a Serat.
	Description string `json:"description"`
	Content     string `json:"content"`
	// The cover image URL of a Serat, shown on detail page.
	CoverImageUrl string `json:"cover_image_url"`
	// The thumbnail image URL of a Serat, shown when retrieved as list.
	ThumbnailImageUrl string       `json:"thumbnail_image_url"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
}
