// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package query

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

// Store every serats of kasusastran.io
type Serat struct {
	ID uuid.UUID `json:"id"`
	// The title of a Serat.
	Title string `json:"title"`
	// The summary of a Serat.
	Description string `json:"description"`
	Content     string `json:"content"`
	// The cover image URL of a Serat, shown on detail page.
	CoverImageUrl string `json:"cover_image_url"`
	// The thumbnail image URL of a Serat, shown when retrieved as list.
	ThumbnailImageUrl string       `json:"thumbnail_image_url"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
}

// Store every users
type User struct {
	// The id of user
	ID uuid.UUID `json:"id"`
	// The name of user
	Name string `json:"name"`
	// The email of user
	Email sql.NullString `json:"email"`
	// The encrypted password of a user
	EncryptedPassword sql.NullString `json:"encrypted_password"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
}

// Store every wulangan (course) of kasusastran.io
type Wulangan struct {
	ID uuid.UUID `json:"id"`
	// The title of a Wulangan.
	Title string `json:"title"`
	// The summary of a Wulangan.
	Description string `json:"description"`
	// The cover image URL of a Wulangan, shown on detail page.
	CoverImageUrl string `json:"cover_image_url"`
	// The thumbnail image URL of a Wulangan, shown when retrieved as list.
	ThumbnailImageUrl string       `json:"thumbnail_image_url"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	DeletedAt         sql.NullTime `json:"deleted_at"`
}

// Store every bab on a wulangan (course) on kasusastran.io
type WulanganBab struct {
	ID uuid.UUID `json:"id"`
	// The title on a Bab of a Wulangan.
	Title string `json:"title"`
	// The summary of a Bab in a Wulangan.
	Description string `json:"description"`
	// Total kaca on a Bab of Wulangan
	KacaCount int32 `json:"kaca_count"`
	// The id of wulangan.
	WulanganID uuid.UUID    `json:"wulangan_id"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	// The Bab order
	Idx sql.NullInt32 `json:"idx"`
}

// Store every kaca of a bab of wulangan (course) on kasusastran.io
type WulanganBabKaca struct {
	ID uuid.UUID `json:"id"`
	// Kaca title.
	Title string `json:"title"`
	// Kaca content as HTML.
	Content string `json:"content"`
	// Bab id of kaca.
	WulanganBabID uuid.UUID    `json:"wulangan_bab_id"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
	// The kaca order inside bab.
	Idx sql.NullInt32 `json:"idx"`
	// The kaca order on wulangan perspective
	Gidx sql.NullInt32 `json:"gidx"`
}
