// Code generated by sqlc. DO NOT EDIT.

package query

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountSerats(ctx context.Context) (int64, error)
	CreateSerat(ctx context.Context, arg *CreateSeratParams) (CreateSeratRow, error)
	DeleteSerat(ctx context.Context, id uuid.UUID) error
	GetSerat(ctx context.Context, id uuid.UUID) (GetSeratRow, error)
	ListSerats(ctx context.Context, arg *ListSeratsParams) ([]ListSeratsRow, error)
	UpdateSerat(ctx context.Context, arg *UpdateSeratParams) (UpdateSeratRow, error)
}

var _ Querier = (*Queries)(nil)
