// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	message "github.com/fikrirnurhidayat/kasusastran/app/domain/message"
	mock "github.com/stretchr/testify/mock"
)

// SessionEventEmitter is an autogenerated mock type for the SessionEventEmitter type
type SessionEventEmitter struct {
	mock.Mock
}

// EmitCreatedEvent provides a mock function with given fields: _a0
func (_m *SessionEventEmitter) EmitCreatedEvent(_a0 *message.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*message.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSessionEventEmitter interface {
	mock.TestingT
	Cleanup(func())
}

// NewSessionEventEmitter creates a new instance of SessionEventEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSessionEventEmitter(t mockConstructorTestingTNewSessionEventEmitter) *SessionEventEmitter {
	mock := &SessionEventEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
