// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/fikrirnurhidayat/kasusastran/app/domain/entity"
	mock "github.com/stretchr/testify/mock"

	svc "github.com/fikrirnurhidayat/kasusastran/app/domain/svc"
)

// CreateWulanganService is an autogenerated mock type for the CreateWulanganService type
type CreateWulanganService struct {
	mock.Mock
}

// Call provides a mock function with given fields: _a0, _a1
func (_m *CreateWulanganService) Call(_a0 context.Context, _a1 *svc.CreateWulanganParams) (*entity.Wulangan, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *entity.Wulangan
	if rf, ok := ret.Get(0).(func(context.Context, *svc.CreateWulanganParams) *entity.Wulangan); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Wulangan)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *svc.CreateWulanganParams) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
