// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DeleteSeratService is an autogenerated mock type for the DeleteSeratService type
type DeleteSeratService struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, id
func (_m *DeleteSeratService) Call(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteSeratService interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteSeratService creates a new instance of DeleteSeratService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteSeratService(t mockConstructorTestingTNewDeleteSeratService) *DeleteSeratService {
	mock := &DeleteSeratService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
