// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/fikrirnurhidayat/api.kasusastran.io/app/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GetSeratService is an autogenerated mock type for the GetSeratService type
type GetSeratService struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, id
func (_m *GetSeratService) Exec(ctx context.Context, id uuid.UUID) (*entity.Serat, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Serat
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Serat); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Serat)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
