// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/fikrirnurhidayat/kasusastran/app/domain/entity"
	mock "github.com/stretchr/testify/mock"

	svc "github.com/fikrirnurhidayat/kasusastran/app/domain/svc"

	uuid "github.com/google/uuid"
)

// UpdateSeratService is an autogenerated mock type for the UpdateSeratService type
type UpdateSeratService struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, id, params
func (_m *UpdateSeratService) Call(ctx context.Context, id uuid.UUID, params *svc.UpdateSeratParams) (*entity.Serat, error) {
	ret := _m.Called(ctx, id, params)

	var r0 *entity.Serat
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *svc.UpdateSeratParams) *entity.Serat); ok {
		r0 = rf(ctx, id, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Serat)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *svc.UpdateSeratParams) error); ok {
		r1 = rf(ctx, id, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
