// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	srv "github.com/fikrirnurhidayat/kasusastran/app/srv"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticationServerSetter is an autogenerated mock type for the AuthenticationServerSetter type
type AuthenticationServerSetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *AuthenticationServerSetter) Execute(_a0 *srv.AuthenticationServer) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewAuthenticationServerSetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthenticationServerSetter creates a new instance of AuthenticationServerSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthenticationServerSetter(t mockConstructorTestingTNewAuthenticationServerSetter) *AuthenticationServerSetter {
	mock := &AuthenticationServerSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
