// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	srv "github.com/fikrirnurhidayat/kasusastran/app/srv"
	mock "github.com/stretchr/testify/mock"
)

// SeratsServerSetter is an autogenerated mock type for the SeratsServerSetter type
type SeratsServerSetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *SeratsServerSetter) Execute(_a0 *srv.SeratsServer) {
	_m.Called(_a0)
}
