// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	srv "github.com/fikrirnurhidayat/kasusastran/app/srv"
	mock "github.com/stretchr/testify/mock"
)

// SeratsServerSetter is an autogenerated mock type for the SeratsServerSetter type
type SeratsServerSetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *SeratsServerSetter) Execute(_a0 *srv.SeratsServer) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewSeratsServerSetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewSeratsServerSetter creates a new instance of SeratsServerSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSeratsServerSetter(t mockConstructorTestingTNewSeratsServerSetter) *SeratsServerSetter {
	mock := &SeratsServerSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
