// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	grpclog "google.golang.org/grpc/grpclog"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// setLogger provides a mock function with given fields: _a0
func (_m *Server) setLogger(_a0 grpclog.LoggerV2) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServer(t mockConstructorTestingTNewServer) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
