// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	srv "github.com/fikrirnurhidayat/kasusastran/app/srv"
	mock "github.com/stretchr/testify/mock"
)

// WulangansServerSetter is an autogenerated mock type for the WulangansServerSetter type
type WulangansServerSetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *WulangansServerSetter) Execute(_a0 *srv.WulangansServer) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewWulangansServerSetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewWulangansServerSetter creates a new instance of WulangansServerSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWulangansServerSetter(t mockConstructorTestingTNewWulangansServerSetter) *WulangansServerSetter {
	mock := &WulangansServerSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
