// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	srv "github.com/fikrirnurhidayat/kasusastran/app/srv"
	mock "github.com/stretchr/testify/mock"
)

// WulangansServerSetter is an autogenerated mock type for the WulangansServerSetter type
type WulangansServerSetter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *WulangansServerSetter) Execute(_a0 *srv.WulangansServer) {
	_m.Called(_a0)
}
